
-- lvim.builtin.which_key.mappings["T"] = {
--   name = "Diagnostics",
--   t = { "<cmd>TroubleToggle<cr>", "Trouble" },
--   w = { "<cmd>TroubleToggle lsp_workspace_diagnostics<cr>", "Workspace" },
--   d = { "<cmd>TroubleToggle lsp_document_diagnostics<cr>", "Document" },
--   q = { "<cmd>TroubleToggle quickfix<cr>", "Quickfix" },
--   l = { "<cmd>TroubleToggle loclist<cr>", "Location list" },
--   r = { "<cmd>TroubleToggle lsp_references<cr>", "References" },
--   -- definition
--   -- ....
-- }
